### ISSUE TITLE
error when executing fish: fish_is_root_user: command not found

### ISSUE THREAD

**Issue by IlijazM** [Bleuzen/linux-setup#2]
When I execute fish under ubuntu I get this error:

```bash
username:~/git/linux-setup$ fish
fish_is_root_user: command not found
~/.config/fish/functions/fish_prompt.fish (line 39): 
    if fish_is_root_user
       ^
in function 'fish_prompt'
in command substitution
~/g/linux-setup (main|✔) ❯ 
```

**Comment by Bleuzen** [comment]
This is because the fish version in Ubuntu repos is too old and nobody cared about it for some time. Now finally it is updated, but will not affect old releases. Upgrading to Ubuntu 22.04 fixes this problem.

22.04 is still in development, but can already be upgraded to with:
```
sudo do-release-upgrade -d
```

If you really don't want to upgrade yet, you can replace the `if fish_is_root_user` check with:
`if contains -- $USER root toor`.
